active: dev

server:
  port: 8082

gateway:
  domain: http://127.0.0.1
  port: 8080

nacos:
  enabled: true
  address: http://127.0.0.1:8848
  username: nacos
  password: nacos
  namespace: 
  group: DEFAULT_GROUP
  dataId:
    # 需要获取的配置文件的dataId
    application: koa-server.yml
    gateway: gateway-server.yml
    redis: redis.yml

rabbitMq:
  enabled: false
  address: http://10.42.45.2:30864
  username: admin
  password: admin123
  queue:
    queue1: xxxxxx;
    queue2: ffffff;

oss:
  enabled: false
  endpoint: xxx.aliyuncs.com,
  accessKeyId: xxxooo,
  accessKeySecret: xxxooo,
  bucket: xx
  dir: oo

redis:
  enabled: false
  host: 127.0.0.1:6379
  port: 6379
  username: 
  password: 
  database: 1